package gazelle

import (
	"fmt"
	"log"
	"os"
	"path/filepath"
	"strings"

	"github.com/bazelbuild/bazel-gazelle/config"
	"github.com/bazelbuild/bazel-gazelle/label"
	"github.com/bazelbuild/bazel-gazelle/repo"
	"github.com/bazelbuild/bazel-gazelle/resolve"
	"github.com/bazelbuild/bazel-gazelle/rule"
	bzl "github.com/bazelbuild/buildtools/build"
	"github.com/emirpasic/gods/sets/treeset"
)

// Name returns the name of the language. This is the prefix of the kinds of
// rules generated. E.g. ts_project
func (*TypeScript) Name() string { return languageName }

// Determine what rule (r) outputs which can be imported.
// For TypeScript this is all the import-paths pointing to files within the rule.
func (ts *TypeScript) Imports(c *config.Config, r *rule.Rule, f *rule.File) []resolve.ImportSpec {
	srcs := r.AttrStrings("srcs")
	provides := make([]resolve.ImportSpec, 0, len(srcs)+1)

	for _, src := range srcs {
		src = filepath.Clean(filepath.Join(f.Pkg, src))
		impt := stripImportExtensions(src)

		provides = append(provides, resolve.ImportSpec{
			Lang: languageName,
			Imp:  impt,
		})

		// Index files can also be imported using only the directory
		if isIndexFile(src) {
			provides = append(provides, resolve.ImportSpec{
				Lang: languageName,
				Imp:  strings.TrimRight(filepath.Dir(impt), indexFileName),
			})
		}
	}

	DEBUG("PROVIDES(%q): %v", r.Name(), provides)

	if len(provides) == 0 {
		return nil
	}

	return provides
}

// Embeds returns a list of labels of rules that the given rule embeds. If
// a rule is embedded by another importable rule of the same language, only
// the embedding rule will be indexed. The embedding rule will inherit
// the imports of the embedded rule.
func (ts *TypeScript) Embeds(r *rule.Rule, from label.Label) []label.Label {
	// TODO(jbedard): implement.
	return make([]label.Label, 0)
}

// Resolve translates imported libraries for a given rule into Bazel
// dependencies. Information about imported libraries is returned for each
// rule generated by language.GenerateRules in
// language.GenerateResult.Imports. Resolve generates a "deps" attribute (or
// the appropriate language-specific equivalent) for each import according to
// language-specific rules and heuristics.
func (ts *TypeScript) Resolve(
	c *config.Config,
	ix *resolve.RuleIndex,
	rc *repo.RemoteCache,
	r *rule.Rule,
	modulesRaw interface{},
	from label.Label,
) {
	deps := ts.ResolveModuleDeps(c, ix, modulesRaw.(*treeset.Set), from)

	DEBUG("RESOLVED(%s): %s => %s", from.Name, modulesRaw.(*treeset.Set).Values(), deps.Values())

	if !deps.Empty() {
		r.SetAttr("deps", convertDependencySetToExpr(deps))
	}
}

func (ts *TypeScript) ResolveModuleDeps(
	c *config.Config,
	ix *resolve.RuleIndex,
	modules *treeset.Set,
	from label.Label,
) *treeset.Set {
	deps := treeset.NewWithStringComparator()

	cfgs := c.Exts[languageName].(Configs)
	cfg := cfgs[from.Pkg]
	hasFatalError := false

	it := modules.Iterator()
	for it.Next() {
		mod := it.Value().(ImportStatement)
		imp := resolve.ImportSpec{
			Lang: languageName,
			Imp:  mod.Path,
		}

		DEBUG("RESOLVE: %q from %q", imp.Imp, from.Name)

		if override, ok := resolve.FindRuleWithOverride(c, imp, languageName); ok {
			if override.Repo == "" {
				override.Repo = from.Repo
			}
			if !override.Equal(from) {
				if override.Repo == from.Repo {
					override.Repo = ""
				}
				dep := override.String()
				deps.Add(dep)
			}
		} else if matches := ix.FindRulesByImportWithConfig(c, imp, languageName); len(matches) > 0 {
			filteredMatches := make([]resolve.FindResult, 0, len(matches))
			for _, match := range matches {
				// Prevent from adding itself as a dependency.
				if !match.IsSelfImport(from) {
					filteredMatches = append(filteredMatches, match)
				}
			}

			DEBUG("MATCHES(%q): %s", from.Name, filteredMatches)

			if len(filteredMatches) == 1 {
				matchLabel := filteredMatches[0].Label.Rel(from.Repo, from.Pkg)
				dep := matchLabel.String()
				deps.Add(dep)
			} else if len(filteredMatches) > 1 {
				err := fmt.Errorf(
					"multiple targets (%s) may be imported with %q in %q "+
						"- this must be fixed using the \"gazelle:resolve\" directive",
					targetListFromResults(filteredMatches), mod.Path, mod.SourcePath)
				log.Println("ERROR: ", err)
				hasFatalError = true
			}
		} else if cfg.ValidateImportStatements() {
			err := fmt.Errorf(
				"Import %[1]q from %[2]q is an unknown dependency. Possible solutions:\n"+
					"\t1. Instruct Gazelle to resolve to a known dependency using the gazelle:resolve directive.\n"+
					"\t2. Ignore the dependency with a comment '# gazelle:%[3]s %[1]s' in the BUILD file",
				mod.Path, mod.SourcePath, IgnoreImportsDirective,
			)
			log.Printf("ERROR: Failed to validate dependencies for target %q. %v", from.String(), err)
			hasFatalError = true
		}
	}

	if hasFatalError {
		os.Exit(1)
	}

	return deps
}

// targetListFromResults returns a string with the human-readable list of
// targets contained in the given results.
func targetListFromResults(results []resolve.FindResult) string {
	list := make([]string, len(results))
	for i, result := range results {
		list[i] = result.Label.String()
	}
	return strings.Join(list, ", ")
}

// convertDependencySetToExpr converts the given set of dependencies to an
// expression to be used in the deps attribute.
func convertDependencySetToExpr(set *treeset.Set) bzl.Expr {
	deps := make([]bzl.Expr, set.Size())
	it := set.Iterator()
	for it.Next() {
		dep := it.Value().(string)
		deps[it.Index()] = &bzl.StringExpr{Value: dep}
	}
	return &bzl.ListExpr{List: deps}
}
