load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "feature2",
    srcs = ["index.ts"],
    declaration = True,
    visibility = ["//visibility:public"],   
    tsconfig = {},
)

