"Basic e2e test for ts_project path mapping support"

module(name = "e2e_path_mapping")

bazel_dep(name = "aspect_rules_ts", version = "0.0.0")
local_path_override(
    module_name = "aspect_rules_ts",
    path = "../..",
)

bazel_dep(name = "aspect_rules_js", version = "3.4.0")

bazel_dep(name = "bazel_skylib", version = "1.8.2", dev_dependency = True)

typescript = use_extension("@aspect_rules_ts//ts:extensions.bzl", "typescript", dev_dependency = True)
typescript.toolchain(
    version_from = "//:package.json",
)
use_repo(typescript, "npm_typescript")
