load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "helper",
    srcs = ["helper.ts", "index.ts"],
    declaration = True,
    visibility = ["//visibility:public"],   
    tsconfig = {},
)

