module(name = "module_a")

bazel_dep(name = "aspect_rules_ts", version = "0.0.0")
local_path_override(
    module_name = "aspect_rules_ts",
    path = "../../..",
)

typescript = use_extension("@aspect_rules_ts//ts:extensions.bzl", "typescript")
typescript.deps(
    version_from = "//:package.json",
)
use_repo(typescript, "npm_typescript")
