workspace(name = "worker")

# Override http_archive for local testing
local_repository(
    name = "aspect_rules_ts",
    path = "../..",
)

load("@aspect_rules_ts//ts:repositories.bzl", "rules_ts_dependencies")
load(":versions.bzl", "SUPPORTED_VERSIONS")

[rules_ts_dependencies(name = "tsc_{version}".format(version = version), ts_version = version) for version in SUPPORTED_VERSIONS]

# Fetch and register node, if you haven't already
load("@rules_nodejs//nodejs:repositories.bzl", "DEFAULT_NODE_VERSION", "nodejs_register_toolchains")

nodejs_register_toolchains(
    name = "node",
    node_version = DEFAULT_NODE_VERSION,
)

