"""Repository rules for fetching pre-compiled TypeScript compiler binaries.

Native TypeScript versions (7+) publish the compiler as a standalone binary in
platform-specific npm packages such as `@typescript/typescript-darwin-arm64`.
These repository rules download only the package for each requested platform and
expose the binary through a Bazel toolchain, so `ts_project` can invoke the
compiler directly without NodeJS.
"""

load("@bazel_tools//tools/build_defs/repo:cache.bzl", "get_default_canonical_id")
load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
load("//ts/private:npm_repositories.bzl", "read_ts_version")
load("//ts/private:versions.bzl", "NATIVE_TYPESCRIPT_VERSIONS")

# Platform-specific npm packages published for native TypeScript versions,
# keyed by the package suffix, e.g. "darwin-arm64" in
# `@typescript/typescript-darwin-arm64`.
#
# npm publishes packages for more platforms than listed here (aix-ppc64,
# linux-loong64, linux-mips64el, linux-ppc64, netbsd-*, openbsd-*, sunos-x64);
# only platforms expressible with constraint values available in the
# "platforms" module version rules_ts depends on are registered by default.
PLATFORMS = {
    "darwin-arm64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:aarch64",
        ],
    ),
    "darwin-x64": struct(
        compatible_with = [
            "@platforms//os:macos",
            "@platforms//cpu:x86_64",
        ],
    ),
    "freebsd-x64": struct(
        compatible_with = [
            "@platforms//os:freebsd",
            "@platforms//cpu:x86_64",
        ],
    ),
    "linux-arm": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:armv7",
        ],
    ),
    "linux-arm64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:aarch64",
        ],
    ),
    "linux-s390x": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:s390x",
        ],
    ),
    "linux-x64": struct(
        compatible_with = [
            "@platforms//os:linux",
            "@platforms//cpu:x86_64",
        ],
    ),
    "win32-arm64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:aarch64",
        ],
    ),
    "win32-x64": struct(
        compatible_with = [
            "@platforms//os:windows",
            "@platforms//cpu:x86_64",
        ],
    ),
}

def _native_typescript_metadata(rctx):
    """Resolve the typescript version for a repo and return (version, native metadata or None)."""
    if not rctx.attr.ts_version and not rctx.attr.ts_version_from:
        return None, None
    version = read_ts_version(rctx, rctx.attr.ts_version, rctx.attr.ts_version_from).version
    return version, NATIVE_TYPESCRIPT_VERSIONS.get(version)

def _tsc_platform_repo_impl(rctx):
    platform = rctx.attr.platform
    version, native_typescript_version = _native_typescript_metadata(rctx)
    if not native_typescript_version:
        fail("""typescript version {} does not publish pre-compiled compiler binaries.
            This repository should only be referenced through the tsc toolchain, which is
            only registered for native TypeScript versions (7.x and greater).""".format(version))

    native_package = "typescript-{}".format(platform)
    integrity = native_typescript_version["native_package_integrities"].get(native_package)
    if not integrity:
        fail("""typescript version {} requires native package {} that is not mirrored in rules_ts.""".format(version, native_package))

    urls = ["https://registry.npmjs.org/@typescript/{native_package}/-/{native_package}-{version}.tgz".format(
        native_package = native_package,
        version = version,
    )]
    rctx.download_and_extract(
        url = urls,
        integrity = integrity,
        canonical_id = get_default_canonical_id(rctx, urls),
    )

    tsc_path = "package/lib/tsc.exe" if platform.startswith("win32") else "package/lib/tsc"
    rctx.file("BUILD.bazel", """# Generated by @aspect_rules_ts//ts/private:tsc_repositories.bzl
load("@aspect_rules_ts//ts/private:tsc_toolchain.bzl", "tsc_toolchain")

# The bundled lib.*.d.ts default libraries must stay siblings of the binary:
# tsc locates them relative to its own (symlink-resolved) location.
tsc_toolchain(
    name = "tsc_toolchain",
    tsc = "{tsc_path}",
    data = glob(["package/lib/*.d.ts"]),
    visibility = ["//visibility:public"],
)
""".format(tsc_path = tsc_path))

    # Bazel <8.3.0 lacks rctx.repo_metadata
    if not hasattr(rctx, "repo_metadata"):
        return None

    return rctx.repo_metadata(reproducible = True)

tsc_platform_repo = repository_rule(
    doc = "Downloads the pre-compiled TypeScript compiler for a single platform.",
    implementation = _tsc_platform_repo_impl,
    attrs = {
        "platform": attr.string(mandatory = True, values = PLATFORMS.keys()),
        "ts_version": attr.string(doc = "Explicit version. If provided, ts_version_from is not read."),
        "ts_version_from": attr.label(doc = "Location of package.json which may have a version for the typescript package."),
    },
)

def _tsc_toolchains_repo_impl(rctx):
    version, native_typescript_version = _native_typescript_metadata(rctx)

    build_content = """# Generated by @aspect_rules_ts//ts/private:tsc_repositories.bzl
#
# The toolchains for the default "npm_typescript" repository are registered by the
# rules_ts MODULE.bazel, so you don't normally need to interact with these targets.
# Toolchains for other repositories can be registered with register_toolchains() or
# selected per-target via ts_project(tsc_toolchain).
"""

    if not version:
        # No typescript repository was configured; leave the repository empty
        # so register_toolchains("//:all") is a no-op.
        build_content += """
# No typescript version is configured, so no tsc toolchains are defined.
"""
    elif not native_typescript_version:
        # Non-native typescript versions ship the compiler as JavaScript; the
        # toolchain wraps the NodeJS-hosted js_binary targets, which run on any
        # exec platform.
        build_content += """
toolchain(
    name = "node_toolchain",
    toolchain = "@{user_repository_name}//:tsc_toolchain",
    toolchain_type = "@aspect_rules_ts//ts:toolchain_type",
)

alias(
    name = "tsc_toolchain",
    actual = "@{user_repository_name}//:tsc_toolchain",
    visibility = ["//visibility:public"],
)
""".format(user_repository_name = rctx.attr.user_repository_name)
    else:
        select_branches = ""
        for platform in rctx.attr.platforms:
            meta = PLATFORMS[platform]
            build_content += """
config_setting(
    name = "{platform}",
    constraint_values = {compatible_with},
)

toolchain(
    name = "{platform}_toolchain",
    exec_compatible_with = {compatible_with},
    toolchain = "@{user_repository_name}_{platform}//:tsc_toolchain",
    toolchain_type = "@aspect_rules_ts//ts:toolchain_type",
)
""".format(
                platform = platform,
                user_repository_name = rctx.attr.user_repository_name,
                compatible_with = meta.compatible_with,
            )
            select_branches += '        ":{platform}": "@{user_repository_name}_{platform}//:tsc_toolchain",\n'.format(
                platform = platform,
                user_repository_name = rctx.attr.user_repository_name,
            )

        # The compiler for whichever platform the consuming configuration runs on.
        # From attributes like ts_project(tsc_toolchain) with cfg = "exec", the
        # select() resolves against the exec platform.
        build_content += """
alias(
    name = "tsc_toolchain",
    actual = select({{
{select_branches}    }}),
    visibility = ["//visibility:public"],
)
""".format(select_branches = select_branches)

    rctx.file("BUILD.bazel", build_content)

    # Bazel <8.3.0 lacks rctx.repo_metadata
    if not hasattr(rctx, "repo_metadata"):
        return None

    return rctx.repo_metadata(reproducible = True)

tsc_toolchains_repo = repository_rule(
    doc = """Creates a repository with tsc toolchain definitions.

    For native (7+) versions a toolchain is defined per platform. These only reference
    the platform-specific repositories through their `toolchain` attribute, so registering
    them does not fetch any compiler binaries; only the toolchain selected for the exec
    platform is ever downloaded.

    For other versions a single platform-independent toolchain is defined, wrapping the
    NodeJS-hosted js_binary targets of the npm_typescript repository.""",
    implementation = _tsc_toolchains_repo_impl,
    attrs = {
        "user_repository_name": attr.string(doc = "base name of the platform-specific repositories"),
        "platforms": attr.string_list(doc = "list of platforms to define toolchains for", default = PLATFORMS.keys()),
        "ts_version": attr.string(doc = "Explicit version. If provided, ts_version_from is not read."),
        "ts_version_from": attr.label(doc = "Location of package.json which may have a version for the typescript package."),
    },
)

def tsc_toolchain_repositories(name, ts_version = None, ts_version_from = None, platforms = PLATFORMS.keys()):
    """Create repositories exposing the native TypeScript compiler.

    - creates a repository for each platform, like "npm_typescript_darwin-arm64", which
      downloads the pre-compiled compiler binary for that platform
    - creates a repository exposing toolchains, like "npm_typescript_toolchains":
      one per platform for native (7+) versions, or a single platform-independent
      toolchain wrapping the NodeJS-hosted compiler for other versions

    The toolchains for the default "npm_typescript" repository name are registered
    by the rules_ts MODULE.bazel. Toolchains for other repository names can either be
    registered by the root module or selected per-target via ts_project(tsc_toolchain).

    Args:
        name: base name for the created repositories; matches the name of the
            npm_typescript repository holding the typescript npm package.
        ts_version: version of the TypeScript compiler.
        ts_version_from: label of a json file which declares a typescript version.
        platforms: list of platforms (must be keys in PLATFORMS) to create toolchains for.
    """
    for platform in platforms:
        maybe(
            tsc_platform_repo,
            name = "{}_{}".format(name, platform),
            platform = platform,
            ts_version = ts_version,
            ts_version_from = ts_version_from,
        )

    maybe(
        tsc_toolchains_repo,
        name = name + "_toolchains",
        user_repository_name = name,
        platforms = platforms,
        ts_version = ts_version,
        ts_version_from = ts_version_from,
    )
