packages:
    - connect_node
    - linked_pkg
    - linked_lib
    - linked_consumer
    - linked_empty_node_modules
    - linked_tsconfig
    - linked_tsconfig_consumer
    - lib_nocompile_linked
    - proto_grpc
