// @generated by protoc-gen-es v2.2.4 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file examples/proto_grpc/stripping/s.proto (package proto_grpc.stripping, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file examples/proto_grpc/stripping/s.proto.
 */
export declare const file_examples_proto_grpc_stripping_s: GenFile;

/**
 * @generated from message proto_grpc.stripping.Empty
 */
export declare type Empty = Message<"proto_grpc.stripping.Empty"> & {
};

/**
 * Describes the message proto_grpc.stripping.Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export declare const EmptySchema: GenMessage<Empty>;

