// @generated by protoc-gen-es v2.2.4 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file post-stripped/stripping/s.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file post-stripped/stripping/s.proto.
 */
export declare const file_post_stripped_stripping_s: GenFile;

/**
 * @generated from message Empty
 */
export declare type Empty = Message<"Empty"> & {
};

/**
 * Describes the message Empty.
 * Use `create(EmptySchema)` to create a new message.
 */
export declare const EmptySchema: GenMessage<Empty>;

