module(
    name = "sub_external",
    version = "0.0.0",
)

bazel_dep(name = "aspect_rules_ts", version = "0.0.0")
local_path_override(
    module_name = "aspect_rules_ts",
    path = "../../..",
)

typescript = use_extension("@aspect_rules_ts//ts:extensions.bzl", "typescript")

# Use an alternate npm_typescript name to workaround https://github.com/aspect-build/rules_ts/issues/483
typescript.deps(
    name = "npm_typescript2",
)
use_repo(typescript, "npm_typescript2")
