// @generated by protoc-gen-connect-query v1.4.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file examples/connect_node/proto/eliza.proto (package connectrpc.eliza.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SayRequest, SayResponse } from "./eliza_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from rpc connectrpc.eliza.v1.ElizaService.Say
 */
export const say: {
      readonly name: "Say",
      readonly I: typeof SayRequest,
      readonly O: typeof SayResponse,
      readonly kind: MethodKind.Unary,
  readonly service: {
    readonly typeName: "connectrpc.eliza.v1.ElizaService"
  }
};
