// @generated by protoc-gen-connect-query v2.0.1 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file examples/connect_node/proto/eliza.proto (package connectrpc.eliza.v1, syntax proto3)
/* eslint-disable */

import { ElizaService } from "./eliza_pb";

/**
 * @generated from rpc connectrpc.eliza.v1.ElizaService.Say
 */
export const say: typeof ElizaService["method"]["say"];
