// @generated by protoc-gen-connect-es v1.4.0 with parameter "keep_empty_files=true,target=js+dts"
// @generated from file examples/proto_grpc/logger.proto (package logger, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { Empty, LogMessage } from "./logger_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service logger.Logger
 */
export declare const Logger: {
  readonly typeName: "logger.Logger",
  readonly methods: {
    /**
     * @generated from rpc logger.Logger.SendLogMessage
     */
    readonly sendLogMessage: {
      readonly name: "SendLogMessage",
      readonly I: typeof LogMessage,
      readonly O: typeof Empty,
      readonly kind: MethodKind.Unary,
    },
  }
};

