load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "logic3",
    srcs = ["index.ts"],
    deps = [
        "//feature4/helper"
    ],
    declaration = True,
    visibility = ["//visibility:public"],   
    tsconfig = {},
)

