load("@aspect_rules_ts//ts:defs.bzl", "ts_project")

ts_project(
    name = "logic3",
    srcs = ["index.ts"],
    declaration = True,
    tsconfig = {},
    visibility = ["//visibility:public"],
    deps = [
        "//feature4/helper",
    ],
)
